#!/bin/sh

sleep 20

# Setting scaling max-min freq
max=$(cat /sys/devices/system/cpu/cpufreq/policy0/cpuinfo_max_freq)
max=$(cat /sys/devices/system/cpu/cpufreq/policy4/cpuinfo_max_freq)
max=$(cat /sys/devices/system/cpu/cpufreq/policy7/cpuinfo_max_freq)
echo "$max" > /sys/devices/system/cpu/cpufreq/policy0/scaling_max_freq
echo "$max" > /sys/devices/system/cpu/cpufreq/policy4/scaling_max_freq
echo "$max" > /sys/devices/system/cpu/cpufreq/policy7/scaling_max_freq
