name: Update Repository from Release

on:
  release:
    types: [published]
  workflow_dispatch:

permissions:
  contents: write

jobs:
  update:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Get latest release info
        id: release
        uses: actions/github-script@v7
        with:
          script: |
            const { data: release } = await github.rest.repos.getLatestRelease({
              owner: context.repo.owner,
              repo: context.repo.repo
            });
            
            console.log('Latest release:', release.tag_name);
            console.log('Release assets:', release.assets.map(a => a.name));
            
            // Find zip file in assets (any .zip file)
            const zipAsset = release.assets.find(asset => 
              asset.name.endsWith('.zip')
            );
            
            if (!zipAsset) {
              throw new Error('No zip file found in release assets');
            }
            
            core.setOutput('version', release.tag_name);
            core.setOutput('zip_url', zipAsset.browser_download_url);
            core.setOutput('zip_name', zipAsset.name);
            core.setOutput('release_body', release.body || '');
            
            return {
              version: release.tag_name,
              zipUrl: zipAsset.browser_download_url,
              zipName: zipAsset.name,
              releaseBody: release.body || ''
            };

      - name: Extract version code from tag
        id: version_info
        run: |
          VERSION="${{ steps.release.outputs.version }}"
          # Extract version code from version (e.g., v4.2.1 -> 421)
          VERSION_CODE=$(echo "$VERSION" | sed 's/v//' | sed 's/\.//' | sed 's/\.//')
          # Or use a more sophisticated approach
          MAJOR=$(echo "$VERSION" | sed 's/v//' | cut -d'.' -f1)
          MINOR=$(echo "$VERSION" | sed 's/v//' | cut -d'.' -f2)
          PATCH=$(echo "$VERSION" | sed 's/v//' | cut -d'.' -f3)
          VERSION_CODE=$((MAJOR * 100 + MINOR * 10 + PATCH))
          
          echo "VERSION_CODE=$VERSION_CODE" >> $GITHUB_ENV
          echo "VERSION=$VERSION" >> $GITHUB_ENV
          echo "Extracted version code: $VERSION_CODE"

      - name: Download and extract zip file
        run: |
          echo "=== Downloading zip file ==="
          wget -O temp_module.zip "${{ steps.release.outputs.zip_url }}"
          
          echo "=== Extracting zip file ==="
          unzip -l temp_module.zip
          
          # Extract to temporary directory
          mkdir -p temp_extract
          unzip temp_module.zip -d temp_extract/
          
          echo "=== Extracted contents ==="
          ls -la temp_extract/

      - name: Update module.prop from extracted files
        run: |
          if [ -f "temp_extract/module.prop" ]; then
            echo "=== Updating module.prop from extracted file ==="
            
            # Backup current module.prop
            [ -f "module.prop" ] && cp module.prop module.prop.bak
            
            # Copy extracted module.prop
            cp temp_extract/module.prop module.prop
            
            # Ensure version and versionCode are correct
            if grep -q "^version=" module.prop; then
              sed -i "s/^version=.*/version=$VERSION/" module.prop
            else
              echo "version=$VERSION" >> module.prop
            fi
            
            if grep -q "^versionCode=" module.prop; then
              sed -i "s/^versionCode=.*/versionCode=$VERSION_CODE/" module.prop
            else
              echo "versionCode=$VERSION_CODE" >> module.prop
            fi
            
            echo "=== Updated module.prop ==="
            cat module.prop
          else
            echo "module.prop not found in extracted files!"
            exit 1
          fi

      - name: Update update.json
        run: |
          cat << EOF > update.json
          {
            "version": "$VERSION",
            "versionCode": "$VERSION_CODE",
            "zipUrl": "${{ steps.release.outputs.zip_url }}",
            "changelog": "https://raw.githubusercontent.com/${{ github.repository }}/main/changelog.md"
          }
          EOF
          
          echo "=== update.json created ==="
          cat update.json

      - name: Update changelog
        run: |
          # Create or update changelog.md
          if [ ! -f "changelog.md" ]; then
            echo "# Changelog" > changelog.md
            echo "" >> changelog.md
          fi
          
          # Check if this version already exists in changelog
          if ! grep -q "## $VERSION" changelog.md; then
            # Add new version entry at the top
            temp_file=$(mktemp)
            echo "# Changelog" > "$temp_file"
            echo "" >> "$temp_file"
            echo "## $VERSION ($(date +%Y-%m-%d))" >> "$temp_file"
            echo "- Updated to version $VERSION" >> "$temp_file"
            echo "- Version code: $VERSION_CODE" >> "$temp_file"
            
            # Add release notes if available
            if [ -n "${{ steps.release.outputs.release_body }}" ]; then
              echo "- Release notes:" >> "$temp_file"
              echo "${{ steps.release.outputs.release_body }}" | sed 's/^/  /' >> "$temp_file"
            fi
            
            echo "" >> "$temp_file"
            
            # Append existing changelog content (skip first line if it's "# Changelog")
            if [ -f "changelog.md" ]; then
              tail -n +2 changelog.md >> "$temp_file"
            fi
            
            mv "$temp_file" changelog.md
            
            echo "=== Updated changelog.md ==="
            head -20 changelog.md
          else
            echo "Version $VERSION already exists in changelog"
          fi

      - name: Update README.md
        run: |
          if [ -f "README.md" ]; then
            echo "=== Updating README.md ==="
            
            # Create backup
            cp README.md README.md.bak
            
            # Update version info in README
            sed -i "s/v[0-9]\+\.[0-9]\+\.[0-9]\+/$VERSION/g" README.md
            sed -i "s/Version: v[0-9]\+\.[0-9]\+\.[0-9]\+/Version: $VERSION/g" README.md
            sed -i "s/Latest: v[0-9]\+\.[0-9]\+\.[0-9]\+/Latest: $VERSION/g" README.md
            sed -i "s/Version Code: [0-9]\+/Version Code: $VERSION_CODE/g" README.md
            
            # Update download links
            sed -i "s|https://github.com/.*/releases/download/v[0-9]\+\.[0-9]\+\.[0-9]\+/.*\.zip|${{ steps.release.outputs.zip_url }}|g" README.md
            
            echo "=== Updated README.md ==="
            head -10 README.md
          else
            echo "README.md not found, skipping update"
          fi

      - name: Update other files if needed
        run: |
          # Update any other files that might contain version info
          echo "=== Checking for other files to update ==="
          
          # Update any .json files with version info
          for file in *.json; do
            if [ -f "$file" ] && [ "$file" != "update.json" ]; then
              if grep -q "version" "$file"; then
                echo "Updating version in $file"
                sed -i "s/\"version\": \"v[0-9]\+\.[0-9]\+\.[0-9]\+\"/\"version\": \"$VERSION\"/g" "$file"
                sed -i "s/\"versionCode\": \"[0-9]\+\"/\"versionCode\": \"$VERSION_CODE\"/g" "$file"
              fi
            fi
          done
          
          # Update any .txt or .md files with version info
          for file in *.txt *.md; do
            if [ -f "$file" ] && [ "$file" != "README.md" ] && [ "$file" != "changelog.md" ]; then
              if grep -q "v[0-9]\+\.[0-9]\+\.[0-9]\+" "$file"; then
                echo "Updating version in $file"
                sed -i "s/v[0-9]\+\.[0-9]\+\.[0-9]\+/$VERSION/g" "$file"
              fi
            fi
          done

      - name: Commit all updated files
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          
          # Add all modified files
          git add .
          
          # Check if there are changes to commit
          if git diff --staged --quiet; then
            echo "No changes to commit"
          else
            git commit -m "🔄 Auto-update repository from release $VERSION [skip ci]"
            git push
          fi
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Cleanup
        run: |
          rm -rf temp_extract temp_module.zip
          rm -f *.bak

      - name: Complete job
        run: |
          echo "=== Repository update completed successfully ==="
          echo "Version: $VERSION"
          echo "Version Code: $VERSION_CODE"
          echo "Zip URL: ${{ steps.release.outputs.zip_url }}"
          echo "Repository updated from release!"
